remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    github: neos-modding-group
  # Minima date format. refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%Y-%m-%d"
title: Neos Modding Group
header_pages:
  - mod-list.md
  - submission-tutorial.md
  - about.md
plugins:
  - jekyll-sitemap
